version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nifi:
    image: mkobit/nifi
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./scripts:/scripts

  # debugging nifi out
  # use this as follows
  # - add processsor "PutTCP"
  #   - Hostname: debug
  #   - Port: 80
  # - connect something that produces text to it
  # - check the logs of it: docker-compose logs -f debug
  debug:
    image: appropriate/nc
    command: nc -l 80

  elasticsearch:
    image: elasticsearch
    ports:
      - '9200:9200'
    command: -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1

  kibana:
    image: kibana
    ports:
      - '5601:5601'

  postgres:
    image: postgres
    volumes:
      - ./postgres_init/:/docker-entrypoint-initdb.d/

  kafka-producer:
    build: kafka_producer
    image: marzolfb/kafka-producer

  nifi-init:
    build: nifi_init
    image: marzolfb/nifi-init
